FROM registry.cn-qingdao.aliyuncs.com/metersphere/ms-node-controller:v1.4.3
MAINTAINER zhangz@goodrain.com

ENV TZ=Asia/Shanghai
ENV HOST_HOSTNAME $HOSTNAME

EXPOSE 8082
VOLUME [ "/opt/metersphere/conf","/jmeter","/opt/metersphere/logs", ]
